---
- name: update all packages on Debain-based
  apt:
    name: "*"
    state: latest
    force_apt_get: true
  when: ansible_facts['os_family']|lower == 'debian'

- name: update all packages on RedHat-based
  yum:
    name: "*"
    state: latest
  when: ansible_facts['os_family']|lower == 'redhat'

- name: update all packages on all another
  package:
    name: "*"
    state: latest
  when: (ansible_facts['os_family']|lower != 'redhat') and 
    (ansible_facts['os_family']|lower != 'debian')
    